# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'basicGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(856, 776)
        self.uploadButton = QtWidgets.QPushButton(Dialog)
        self.uploadButton.setGeometry(QtCore.QRect(440, 20, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.uploadButton.setFont(font)
        self.uploadButton.setObjectName("uploadButton")
        self.methodComboBox = QtWidgets.QComboBox(Dialog)
        self.methodComboBox.setGeometry(QtCore.QRect(10, 90, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.methodComboBox.setFont(font)
        self.methodComboBox.setObjectName("methodComboBox")
        self.methodComboBox.addItem("")
        self.methodComboBox.addItem("")
        self.methodComboBox.addItem("")
        self.plotLabel = QtWidgets.QLabel(Dialog)
        self.plotLabel.setGeometry(QtCore.QRect(110, 190, 641, 481))
        self.plotLabel.setText("")
        self.plotLabel.setPixmap(QtGui.QPixmap("Figure_2.png"))
        self.plotLabel.setScaledContents(False)
        self.plotLabel.setObjectName("plotLabel")
        self.pathLineEdit = QtWidgets.QLineEdit(Dialog)
        self.pathLineEdit.setGeometry(QtCore.QRect(10, 20, 291, 41))
        self.pathLineEdit.setObjectName("pathLineEdit")
        self.browseButton = QtWidgets.QPushButton(Dialog)
        self.browseButton.setGeometry(QtCore.QRect(320, 20, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.browseButton.setFont(font)
        self.browseButton.setObjectName("browseButton")
        self.saveButton = QtWidgets.QPushButton(Dialog)
        self.saveButton.setGeometry(QtCore.QRect(620, 690, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.saveButton.setFont(font)
        self.saveButton.setObjectName("saveButton")
        self.nextButton = QtWidgets.QPushButton(Dialog)
        self.nextButton.setGeometry(QtCore.QRect(770, 400, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nextButton.setFont(font)
        self.nextButton.setObjectName("nextButton")
        self.previousButton = QtWidgets.QPushButton(Dialog)
        self.previousButton.setGeometry(QtCore.QRect(10, 400, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.previousButton.setFont(font)
        self.previousButton.setObjectName("previousButton")
        self.withCorrectionRadioButton = QtWidgets.QRadioButton(Dialog)
        self.withCorrectionRadioButton.setGeometry(QtCore.QRect(490, 86, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.withCorrectionRadioButton.setFont(font)
        self.withCorrectionRadioButton.setObjectName("withCorrectionRadioButton")
        self.withoutCorrectionRadioButton = QtWidgets.QRadioButton(Dialog)
        self.withoutCorrectionRadioButton.setGeometry(QtCore.QRect(490, 116, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.withoutCorrectionRadioButton.setFont(font)
        self.withoutCorrectionRadioButton.setObjectName("withoutCorrectionRadioButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.uploadButton.setText(_translate("Dialog", "Upload file"))
        self.methodComboBox.setItemText(0, _translate("Dialog", "Method 1"))
        self.methodComboBox.setItemText(1, _translate("Dialog", "Method 2"))
        self.methodComboBox.setItemText(2, _translate("Dialog", "Method 3"))
        self.browseButton.setText(_translate("Dialog", "Browse"))
        self.saveButton.setText(_translate("Dialog", "Save plot"))
        self.nextButton.setText(_translate("Dialog", "Next"))
        self.previousButton.setText(_translate("Dialog", "Previous"))
        self.withCorrectionRadioButton.setText(_translate("Dialog", "With signal correction"))
        self.withoutCorrectionRadioButton.setText(_translate("Dialog", "Without signal correction"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
