# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firstWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from GUI.secondWindow import Ui_secondWindow
from GUI.thirdWindow import Ui_thirdWindow
import dataExtraction



class Ui_firstWindow(object):
    # function opening second window (after pushing a button)
    def openSecondWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_secondWindow()
        self.ui.setupUi(self.window)
        firstWindow.hide()
        self.window.show()

    # function browsing files and setting path to file
    # browses only for asc files
    # now start path is my desktop, in the end it will be computer
    # after setting path it is enabled to go to the second window
    def browseFiles(self):
        fileName = QFileDialog.getOpenFileName(self.centralwidget, 'Open file', 'C:/Users/Julia/Desktop',
                                               'ascii and text files (*.asc *.txt)')
        self.pathLineEdit.setText(fileName[0])
        if self.pathLineEdit.text() is not None:
            self.uploadButton.setEnabled(True)
            self.nextButton.setEnabled(True)
        print(self.pathLineEdit.text())

    # function extracting input data from input file while clicking nextButton
    def uploadInputData(self):
        dataExtraction.extractInputData(self.pathLineEdit.text())
        dataExtraction.extractSamplingRate(self.pathLineEdit.text())


    def setupUi(self, firstWindow):
        firstWindow.setObjectName("firstWindow")
        firstWindow.resize(778, 415)
        self.centralwidget = QtWidgets.QWidget(firstWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(10, 50, 761, 91))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")

        self.browseButton = QtWidgets.QPushButton(self.centralwidget)
        self.browseButton.setGeometry(QtCore.QRect(570, 220, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.browseButton.setFont(font)
        self.browseButton.setObjectName("browseButton")

        # connecting clicking browseButton with function which browses file (browseFiles)
        self.browseButton.clicked.connect(self.browseFiles)

        self.pathLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.pathLineEdit.setGeometry(QtCore.QRect(140, 220, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pathLineEdit.setFont(font)
        self.pathLineEdit.setReadOnly(True)
        self.pathLineEdit.setObjectName("pathLineEdit")

        self.orderLabel = QtWidgets.QLabel(self.centralwidget)
        self.orderLabel.setGeometry(QtCore.QRect(140, 170, 511, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.orderLabel.setFont(font)
        self.orderLabel.setObjectName("orderLabel")

        self.nextButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextButton.setGeometry(QtCore.QRect(460, 330, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nextButton.setFont(font)
        self.nextButton.setObjectName("nextButton")
        # setting nextButton to disabled at the beginning
        self.nextButton.setEnabled(False)

        # connecting clicking nextButton with function which opens second window
        self.nextButton.clicked.connect(self.openSecondWindow)

        # connecting clicking nextButton with function which extracts input data
        # self.nextButton.clicked.connect(self.extractInputData)

        self.uploadButton = QtWidgets.QPushButton(self.centralwidget)
        self.uploadButton.setGeometry(QtCore.QRect(140, 280, 511, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.uploadButton.setFont(font)
        self.uploadButton.setObjectName("uploadButton")
        # setting uploadButton to disabled at the beginning
        self.uploadButton.setEnabled(False)

        # connecting clicking uploadButton with function which extracts input data
        self.uploadButton.clicked.connect(self.uploadInputData)

        firstWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(firstWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 778, 21))
        self.menubar.setObjectName("menubar")
        firstWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(firstWindow)
        self.statusbar.setObjectName("statusbar")
        firstWindow.setStatusBar(self.statusbar)

        self.retranslateUi(firstWindow)
        QtCore.QMetaObject.connectSlotsByName(firstWindow)

    def retranslateUi(self, firstWindow):
        _translate = QtCore.QCoreApplication.translate
        firstWindow.setWindowTitle(_translate("firstWindow", "MainWindow"))
        self.titleLabel.setText(_translate("firstWindow", "Program detecting artifacts in EEG"))
        self.browseButton.setText(_translate("firstWindow", "Browse"))
        self.orderLabel.setText(_translate("firstWindow", "Please choose the file you want to be processed:"))
        self.nextButton.setText(_translate("firstWindow", "Go to next step"))
        self.uploadButton.setText(_translate("firstWindow", "Upload file"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    firstWindow = QtWidgets.QMainWindow()
    ui = Ui_firstWindow()
    ui.setupUi(firstWindow)
    firstWindow.show()
    sys.exit(app.exec_())
