# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firstWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from GUI.secondWindow import Ui_secondWindow


class Ui_firstWindow(object):
    def openSecondWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_secondWindow()
        self.ui.setupUi(self.window)
        firstWindow.hide()
        self.window.show()

    def browseFiles(self):
        fileName = QFileDialog.getOpenFileName(self.centralwidget, 'Open file', 'C:/Users', 'asc files (*.asc)')
        self.pathLineEdit.setText(fileName[0])

    def setupUi(self, firstWindow):
        firstWindow.setObjectName("firstWindow")
        firstWindow.resize(778, 415)
        self.centralwidget = QtWidgets.QWidget(firstWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(10, 50, 761, 91))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")


        self.browseButton = QtWidgets.QPushButton(self.centralwidget)
        self.browseButton.setGeometry(QtCore.QRect(570, 220, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.browseButton.setFont(font)
        self.browseButton.setObjectName("browseButton")

        self.browseButton.clicked.connect(self.browseFiles)


        self.pathLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.pathLineEdit.setGeometry(QtCore.QRect(140, 220, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pathLineEdit.setFont(font)
        self.pathLineEdit.setObjectName("pathLineEdit")

        self.orderLabel = QtWidgets.QLabel(self.centralwidget)
        self.orderLabel.setGeometry(QtCore.QRect(140, 170, 511, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.orderLabel.setFont(font)
        self.orderLabel.setObjectName("orderLabel")

        self.nextButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextButton.setGeometry(QtCore.QRect(460, 330, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nextButton.setFont(font)
        self.nextButton.setObjectName("nextButton")

        self.nextButton.clicked.connect(self.openSecondWindow)

        firstWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(firstWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 778, 21))
        self.menubar.setObjectName("menubar")
        firstWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(firstWindow)
        self.statusbar.setObjectName("statusbar")
        firstWindow.setStatusBar(self.statusbar)

        self.retranslateUi(firstWindow)
        QtCore.QMetaObject.connectSlotsByName(firstWindow)

    def retranslateUi(self, firstWindow):
        _translate = QtCore.QCoreApplication.translate
        firstWindow.setWindowTitle(_translate("firstWindow", "MainWindow"))
        self.titleLabel.setText(_translate("firstWindow", "Program detecting artifacts in EEG"))
        self.browseButton.setText(_translate("firstWindow", "Browse"))
        self.orderLabel.setText(_translate("firstWindow", "Please choose the file you want to be processed:"))
        self.nextButton.setText(_translate("firstWindow", "Go to next step"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    firstWindow = QtWidgets.QMainWindow()
    ui = Ui_firstWindow()
    ui.setupUi(firstWindow)
    firstWindow.show()
    sys.exit(app.exec_())
