# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from functools import partial
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
import artifactDetection as aD
import dataExtraction as dE
import graphPlotting as gP


class Ui_MainWindow(object):
    inputData = []
    detectionMethod = ""
    isArtifact = []
    blockNumber = 0
    message = ""

    def browseFiles(self):
        fileName = QFileDialog.getOpenFileName(self.centralwidget, "Open file", "C:/Users/Julia/Desktop",
                                               "ascii (*.asc)")
        self.pathLineEdit.setText(fileName[0])
        if self.pathLineEdit.text() is not None:
            self.uploadButton.setEnabled(True)

    def uploadFile(self):
        self.inputData = dE.extractInputData(self.pathLineEdit.text())
        self.methodComboBox.setEnabled(True)
        self.performButton.setEnabled(True)

    def chooseDetectionMethod(self):
        index = self.methodComboBox.currentIndex()
        if index == 0:
            self.detectionMethod = "performEEPDetection"
        elif index == 1:
            self.detectionMethod = "performECGDetection"
        elif index == 2:
            self.detectionMethod = "performLFPDetection"

    def performDetection(self):
        if self.detectionMethod == "performEEPDetection":
            result = aD.performEEPDetection(self.inputData)
        elif self.detectionMethod == "performECGDetection":
            result = aD.performECGDetection(self.inputData)
        elif self.detectionMethod == "performLFPDetection":
            result = aD.performLFPDetection(self.inputData)
        self.isArtifact = result[0]
        self.blockNumber = len(self.isArtifact)
        self.message = result[1]
        print("Great!")

    def plotGraph(self):
        gP.plotAllBlocks(self.inputData, self.isArtifact, self.message)
        self.plotLabel


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1277, 934)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")


        self.pathLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.pathLineEdit.setGeometry(QtCore.QRect(10, 20, 611, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pathLineEdit.setFont(font)
        self.pathLineEdit.setObjectName("pathLineEdit")
        self.pathLineEdit.setReadOnly(True)



        self.browseButton = QtWidgets.QPushButton(self.centralwidget)
        self.browseButton.setGeometry(QtCore.QRect(630, 20, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.browseButton.setFont(font)
        self.browseButton.setObjectName("browseButton")

        # connecting clicking browseButton with function which browses file (browseFiles)
        self.browseButton.clicked.connect(self.browseFiles)



        self.uploadButton = QtWidgets.QPushButton(self.centralwidget)
        self.uploadButton.setGeometry(QtCore.QRect(770, 20, 491, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.uploadButton.setFont(font)
        self.uploadButton.setObjectName("uploadButton")
        self.uploadButton.setEnabled(False)

        # connecting clicking uploadButton with function which uploads file (uploadFile)
        self.uploadButton.clicked.connect(self.uploadFile)



        self.methodComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.methodComboBox.setGeometry(QtCore.QRect(10, 80, 611, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.methodComboBox.setFont(font)
        self.methodComboBox.setObjectName("methodComboBox")
        self.methodComboBox.addItem("")
        self.methodComboBox.addItem("")
        self.methodComboBox.addItem("")
        self.methodComboBox.setEnabled(False)

        self.methodComboBox.activated.connect(self.chooseDetectionMethod)


        self.performButton = QtWidgets.QPushButton(self.centralwidget)
        self.performButton.setGeometry(QtCore.QRect(630, 80, 631, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.performButton.setFont(font)
        self.performButton.setObjectName("performButton")
        self.performButton.setEnabled(False)

        # connecting clicking performButton with function which performs artifact's detection (performDetection)
        self.performButton.clicked.connect(self.performDetection)


        self.previousButton = QtWidgets.QPushButton(self.centralwidget)
        self.previousButton.setGeometry(QtCore.QRect(20, 450, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.previousButton.setFont(font)
        self.previousButton.setObjectName("previousButton")
        self.previousButton.setEnabled(False)



        self.nextButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextButton.setGeometry(QtCore.QRect(1130, 450, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nextButton.setFont(font)
        self.nextButton.setObjectName("nextButton")
        self.nextButton.setEnabled(False)

        self.nextButton.clicked.connect(self.plotGraph)



        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(1050, 860, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.saveButton.setFont(font)
        self.saveButton.setObjectName("saveButton")
        self.saveButton.setEnabled(False)



        self.plotLabel = QtWidgets.QLabel(self.centralwidget)
        self.plotLabel.setGeometry(QtCore.QRect(290, 150, 811, 711))
        self.plotLabel.setText("")
        self.plotLabel.setObjectName("plotLabel")





        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1277, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.browseButton.setText(_translate("MainWindow", "Browse"))
        self.uploadButton.setText(_translate("MainWindow", "Upload file"))
        self.methodComboBox.setItemText(0, _translate("MainWindow", "Method 1: detect external electrostatic potentials"))
        self.methodComboBox.setItemText(1, _translate("MainWindow", "Method 2: detect potentials derived from ECG"))
        self.methodComboBox.setItemText(2, _translate("MainWindow", "Method 3: detect low-frequency potentials"))
        self.performButton.setText(_translate("MainWindow", "Perform artifact detection"))
        self.previousButton.setText(_translate("MainWindow", "Previous"))
        self.nextButton.setText(_translate("MainWindow", "Next"))
        self.saveButton.setText(_translate("MainWindow", "Save plot"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
